labels:
  - 1
  - 2
rand_seed: 0
processed_data_dir: ../processed_data
data:
  path: ../data/amazon_reviews.csv
  small_dataset: False
  small_dataset_size: 100
feature:
  verctorizers:
    # - CountVectorizer
    # - TfidfVectorizer
  ngram_range:
    # - (1,1)
    # - (2,2)
    # - (5,5)
  max_feature:
    # - 5
    # - 50
    # - 200
    # - 1000
  # is_stem: False # This parameter is for word stemming. You can set this parameter False for accelerating
  # is_stopwords: False # This parameter is for removing stopwords. You can set this parameter False for accelerating
train:
  fig_dir: ../result_figures
  log_dir: ..
test:
  models:
    - model: lr
      verctorizers: TfidfVectorizer
      ngram_range: (2,2)
      max_feature: 1000
    - model: nb
      verctorizers: TfidfVectorizer
      ngram_range: (5,5)
      max_feature: 200
    - model: nc
      verctorizers: TfidfVectorizer
      ngram_range: (2,2)
      max_feature: 200